#!/bin/bash 
### BEGIN INIT INFO
# Provides:             naspi-pd
# Required-Start:       $remote_fs dbus udev
# Required-Stop:        $remote_fs dbus udev
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    NAS-Pi PHP Backend Daemon
# Description:          Handles administration of your Raspberry Pi using NAS-Pi.
### END INIT INFO
PROG="naspi"
INSTALL_DIR="/usr/share/$PROG"
DAEMON_SCRIPT="pd.php"
DAEMON_PATH="$INSTALL_DIR/pd"
LOG="/var/log/naspid.log"
ERRORS="$INSTALL_DIR"/errors
CONFIG=/etc/$PROG/${PROG}.conf

. $ERRORS

error() {
	echo "[ ERROR $1 ] ${@:2}"
	exit "$1"
}

start() {
	echo 'rm "/tmp/naspi/pd/pd.sock"' >> $LOG
	rm "/tmp/naspi/pd/pd.sock"
	$DAEMON_PATH/$DAEMON_SCRIPT start 2>&1 &
}

stop() {
	echo "$DAEMON_PATH/$DAEMON_SCRIPT stop 2>&1 &" >> $LOG
	$DAEMON_PATH/$DAEMON_SCRIPT stop 2>&1 &
}


if [[ $(id -u) != 0 ]]&&[[ $(id -g) != 0 ]]; then
	error "${E_ROOT[0]}" "${E_ROOT[1]}"
fi

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload|restart)
		stop
		start
		;;
	**)
		error "${E_USAGE[0]}" "$E_USAGE[1]}"
		;;
esac

:
