#!/bin/bash 
### BEGIN INIT INFO
# Provides:             naspid
# Required-Start:       $remote_fs dbus udev
# Required-Stop:        $remote_fs dbus udev
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Network Attached Storage for Raspberry PI Daemon
# Description:          Mounts and unmounts user defined file systems using the NASPI
#                       Web Administation Utility
### END INIT INFO
PROG="naspid"
PROG_PATH="/usr/bin"
RUN_PATH="/var/lock"
export NASPID_LOCK_FILE=$RUN_PATH/${PROG}.lock
ETC_PATH="/etc/naspi"
ERRORS=$ETC_PATH/errors
CONFIG=$ETC_PATH/${PROG}.conf

. $ERRORS

error() {
	echo "ERROR:$@" 1>&2
	exit $1
}

start() {
	if [ -e "$NASPID_LOCK_FILE" ]; then
		error $E_START $M_START
	else
		$PROG_PATH/$PROG start 2>&1 &
		touch "$NASPID_LOCK_FILE"
	fi
}

stop() {
	if [ -e "$NASPID_LOCK_FILE" ]; then
		export RUN=FALSE
		$PROG_PATH/$PROG stop 2>&1 &
	else
		error $E_STOP $M_STOP
	fi
}


if [ "$(id -u)" != "0" ]; then
	error $E_ROOT $M_ROOT
fi

case "$1" in
	start)
		start
		echo "$PROG started"
		exit 0
	;;
	stop)
		stop
		echo "$PROG stopped"
		exit 0
	;;
	reload|restart|force-reload)
		[[ -e $NASPID_LOCK_FILE ]] && stop
		start
		echo "$PROG restarted" >> $LOG &
		exit 0
		;;
	**)
		error $E_USAGE $M_USAGE
		;;
esac

:
